---
:DCHC: Taiga.A
:dchc: Taiga.A
:masses: massess
:[MOB]DanielKuo: DanielKuo
:dognoyuutsu: dognoyuutsu
:caesars: Caesar Wang
:danielkuo: danielkuo
:[KOKA]Altria: roctaiwan
:Guderian117: Guderian117
:[OH]GOURRYNSX: GOURRYNSX
:seach: seach
:Nekolan: Nekolan
:op88675555: op8867555
:wallae82: wallace82
:tohisworld: ToHisWorld
:[koka]garylin: Gary Lin
:huaslove: Hua's Love
:samkong: Sam Kong
:hayibara-working: hayibara_Ai
:[oh]xchengx: xChenGx
:state-ray-plans: State ray plans
:eoc_uuoouu: uuoouu
:ntr77819: NTB77819
:tzuliang: Tzu Liang
:royaltaiwan: Royal Taiwan
:wacow: Wa cow
:donkilu: Donki Lu
:ljosalfar: Ljosalfar
:[koka]aili: roctaiwan
:liencin: suliencin
:benyang: Ben Yang
:ss2hmxrs3: s2hmxrs3
:alsoou: Also Ou
:beaconzh: Beacon.Zh
:seisei: sei sei
:marktseng: Mark Tseng
:ck001231: Mark Tseng
:gilgalad: Ereinion Gilgalad
:op8867555: op8867555
:h-dora: H.dora
:crimsonsmith: crimsonsmith
:chise_e_tamai: Chise E. Tamai
:yomila: yomila
:youngwow: Youngwow
:xchengx: xChenGx
:hdora: H.dora
:schiellsdao: Schiells Dao
:sjing1205: sjing1205
:robertdog12: robertdog12
:omr_ding: OMR.Ding
:mr_oh: Mr.OH
:tgoc: T.G.O.C
:plumgreensweat: plumgreensweat
:apieceoffeces: Apiece of feces
:kouki: kouki shan
:scocansajr: scocansa.Jr
:edwish: edwish
:alberttseng: albert tseng
:kouki_ashan: kouki shan
:gourrynsx|sleepzzz: GOURRYNSX
:fight: hunter huang
:eddy8288: eddy8288
:sportkung: Sport Kung
:wang_zick: wang zick
:pussatsouthern: PussAtSouthern_TW
:paul7373_: robertdog12
:s871101c: s871101c
:sunny_: Sunny Chaung
:anasvella: Anas Vella
:sunnychaung: Sunny Chaung
:stylefeng: crimsonsmith
:hallermann: Hallermann
:[eroc]crimsonsmith: crimsonsmith
:dragoncavalry: Dragon Cavalry
:reching: reChing
:[mod]reching: reChing
:flyskypie: flypie
:pussatsoutherntw: PussAtSouthern_TW
:zimba: z imba
:[mob]xsaanbx: xSaanbx
:joe5978ex: JOE5978
:sangokk: Sango.KK
:kabuyaptt: KabuyaPtt
:klonoa: klonoa wind
:jo00xd[jjqoo]: jjQoo
:[mob]barryyin: barryyin
:sango_kk: Sango.KK
:flyingskull: Flying Skull
:breed_cn: Breed.cn
:jehoahaz: jehoahaz.lee.chunwah
:jehoahaz_lee_chunwah: jehoahaz.lee.chunwah
:hll_826_lee: jehoahaz.lee.chunwah
:blue_s: Blue.S
:moodss_: moodss
:moodss: MoodsS
:veronica_lin: Veronica Lin
:fly_yui: FLY.YUI
:elpsycongroo: El Psy Congroo
:manaitanoneko: ManaitaNoNeko
:moodss-mob: MoodsS
:apiceoffeces: Apiece of feces
:hex: reChing
:phychem: Singying
:hsr: touck
:paoyinchu: Paoyin_Chu
:neveraire: Never Aire
:protonted: PROTONTED
:lother: Einsam Lother
:chin_yi_hsu: Chin Yi Hsu
:kamira999: kamira999
:[oh-ii]1212123q: 1212123q
:utahime_chrome: utahime chrome
:esra: Esra_Fuo
:myexp: myexp
:robertdog17: e6w17uver
:robertdog99: robertdog12
:strangerthe: strangerthe
:joeding: Joe Ding
:coffeeeroc: coFFee Eroc
:[mob]5566: '55667788'
:autohad: AutoHAD
:pickuse: pickuse0.0
:solong: s871101c
:creamsauce: CreamSauce
:ss1850705: ss1850705
:chuth: Chuth
:kugyu: K u g y u
:famio: famio.wong
:doomg4ster1: kugyu
:aangqq: AangQQQ
:chase_yang: Chase.Yang
:tounosiki: douno siki
:ryuzaki_tsunayoshi: Ryuzaki19931211
:[mob]s871101c: s871101c
:[fhef]ryuzaki_tsunayoshi: Ryuzaki19931211
:o0kuan0o: 0KUAN0
:yuxin: JingYuXin
:lovervv: loverV.V
:k-kotonoha: K.Kotonoha
:[d3]chuth: Chuth
:danielusss: danielus10
:synex520: synex520
:xusily: Xusily
:seaforest: 100cebseaweed
:undeadkenny: Undead.Kenny
:cip604: cip604
:smartxdd: I am dd
:handson: I AM DD
:pleaseyou: i am dd
:bletch: i am dd
:smart: i am dd
:mib_ee0ric: i am dd
:morton: i am dd
:jasper: i am dd
:mini: miniptt
:ck09800462: ck11115
:weirdo: I am DD
:guacamole: i am dd
:spookyman: SpookyMan
:axbxsd10: AXBXSD10
:fight_fot_taiwan: fight for taiwan
:peter2081: PETER20801
