production:
  nick: ow_calc_v3
  server: irc.rizon.net
  password: 
  channels: [ '#PTT_Formosa', '#roc', '#ROCAS']
  admin_password: 

development:
  nick: ow_calc_test
  server: irc.rizon.net
  password:
  channels: ['#lother']
  admin_password: 
