production:
  nick: ow_calc_v3
  server: irc.rizon.net
  password: helloword
  channels: [ '#PTT_Formosa', '#roc', '#ROCAS','#lother']
  admin_password: hello

development:
  nick: ow_calc_test_l
  server: irc.mibbit.net
  password:
  channels: ['#ow_calc_test']
  admin_password: hello
