production:
  nick: ow_calc
  server: irc.rizon.net
  password: 
  channels: [ '#PTT_Formosa', '#roc', '#ROCAS']
  admin_password: 

development:
  nick: ow_calc_test_l
  server: irc.mibbit.net
  password:
  channels: ['#ow_calc_test']
  admin_password: 
